/**
 * An enum used to provide different types of text styles
 */
export enum TextPresetStyles {
  BODY_REGULAR = 'bodyRegular',
  BUTTON_1 = 'button1',
  BUTTON_2 = 'button2',
  BADGE_1 = 'badge1',
  BADGE_2 = 'badge2',
  BUTTON_3 = 'button3',
  CAPTION_1 = 'caption1',
  CAPTION_2 = 'caption2',
  DESCRIPTION = 'description',
  DESCRIPTION_SMALL = 'descriptionSmall',
  DESCRIPTION_LARGE = 'descriptionLarge',
  DESCRIPTION_SARA = 'descriptionSara',
  DEFAULT = 'default',
  FOOT_NOTE = 'footNote',
  FOOT_NOTE_HEAVY = 'footNoteHeavy',
  FOOT_NOTE_BOLD = 'fontNoteBold',
  FOOT_NOTE_ULTRA_BOLD = 'fontNoteUltraBold',
  FOOT_NOTE_BOLD_STATIC = 'fontNoteBoldStatic',
  HEADLINE_DARK = 'headlineDark',
  LARGE_TITLE = 'largeTitle',
  MEDIUM_TITLE = 'mediumTitle',
  SMALL_TITLE = 'smallTitle',
  SMALL_TITLE_BOLD = 'smallTittleBold',
  SUB_HEADLINE = 'subHeadline',
  SUB_HEADLINE_REGULAR = 'subHeadlineRegular',
  SUB_HEADLINE1 = 'subHeadline1',
  SUB_HEADLINE2 = 'subHeadline2',
  SUB_HEADLINE1_HEV = 'subHeadline1Hev',
  TEXT_ERROR = 'textError',
  TEXT_INPUT = 'textInput',
  TEXT_INPUT_DISABLED = 'textInputDisabled',
  TEXT_LABEL = 'textLabel',
  TITLE = 'title',
  MINI_FONT = 'miniFont',
  MINI_FONT_REGULAR = 'miniFontRegular',
  CAPTION_3 = 'caption3',
  CAPTION_4 = 'caption4',
  CAPTION_5 = 'caption5',
  CAPTION_6 = 'caption6',
  CAPTION_7 = 'caption7',
  TITLE_HUGE = 'titleHuge',
  TITLE_MEDIUM = 'titleMedium',
  TITLE_CIRCULAR = 'titleCircular',
  TITLE_BOLD = 'titleBold',
  MINI_FONT_SARA = 'miniFontSara',
  MINI_COUNT = 'miniCount',
  TITLE_CIRCULAR_BOLD = 'TitleCircularBold',
}

/**
 * An enum used to provide different types of font weight
 */
export enum TextFontWeightTypes {
  THIN = '100',
  LIGHT = '200',
  BOOK = '300',
  REGULAR = '400',
  MEDIUM = '500',
  SEMI_BOLD = '600',
  BOLD = '700',
  EXTRA_BOLD = '800',
  ULTRA_BOLD = '900',
  NORMAL = 'normal',
  BOLD_TEXT = 'bold',
}
