export enum ICON_TYPES {
  ACCESS_TIME = 'accessTime',
  ADD = 'add',
  ARCHIVE_ICON = 'archiveIcon',
  ARROW_RIGHT = 'arrowRight',
  BACK = 'back',
  BELL = 'bell',
  CALENDAR = 'calendar',
  CHALLENGES_TAB = 'challengesTab',
  CHALLENGES_TAB_FILLED = 'challengesTabFilled',
  CHECK_CIRCLE = 'checkCircle',
  CHECK_CIRCLE_FILLED = 'checkCircleFilled',
  CLOSE = 'close',
  COUNTDOWN = 'countdown',
  CROSS = 'cross',
  CYCLING = 'cycling',
  DELETE = 'delete',
  DOWN_ARROW = 'downArrow',
  DROP_DOWN = 'dropDown',
  DROP_UP = 'dropUp',
  EDIT = 'edit',
  EMAIL = 'email',
  ENVELOPE_ICON = 'envelope',
  ERROR = 'error',
  EXIT = 'exit',
  FLAG = 'flag',
  GREEN_TICK = 'green_tick',
  HOME_TAB = 'homeTab',
  HOME_TAB_FILLED = 'homeTabFilled',
  JOINED = 'joined',
  LINK_ICON = 'linkIcon',
  LOCK_PASS = 'lockPass',
  LOCK_QUESTION = 'lockQuestion',
  MENU = 'menu',
  MESSAGE = 'message',
  MY_CREATE_TEAM = 'myCreateTeam',
  PEOPLE = 'people',
  PERSON_ICON = 'personIcon',
  RED_CROSS = 'redCross',
  REWARD_MEDAL = 'rewardMedal',
  REWARD_MEDAL_FILLED = 'rewardMedalFilled',
  REWARD_TAB = 'rewardTab',
  REWARD_TAB_FILLED = 'rewardTabFilled',
  RUNNING = 'running',
  SAVE = 'save',
  SEARCH = 'search',
  SEND = 'send',
  SHARE = 'share',
  STAR = 'star',
  STAR_FILLED = 'starFilled',
  SYNC = 'sync',
  TEAM = 'team',
  TEAM_TAB = 'teamTab',
  TEAM_TAB_FILLED = 'teamTabFilled',
  TICK = 'tick',
  TICK_2 = 'tick2',
  TICK_PERSON = 'TICK_PERSON',
  TILDE_CIRCLE = 'tildeCircle',
  TIMER = 'timer',
  THUMB_UP = 'thumb_up',
  TRACKER_TAB = 'trackerTab',
  TRACKER_TAB_FILLED = 'trackerTabFilled',
  UP_ARROW = 'upArrow',
  VISIBILITY_OFF = 'visibilityOff',
  VISIBILITY_ON = 'visibilityOn',
  WALKING_BLUE = 'walkingBlue',
  WHEEL_CHAIR = 'wheelChair',
  YELLOW_WATCH = 'yellowWatch',
}

export const icons = {
  [ICON_TYPES.ACCESS_TIME]: require('../../assets/images/icons/access_time.png'),
  [ICON_TYPES.ADD]: require('../../assets/images/icons/add.png'),
  [ICON_TYPES.ARCHIVE_ICON]: require('../../assets/images/icons/archive_icon.png'),
  [ICON_TYPES.ARROW_RIGHT]: require('../../assets/images/icons/arrow_right.png'),
  [ICON_TYPES.BACK]: require('../../assets/images/icons/arrow_back.png'),
  [ICON_TYPES.BELL]: require('../../assets/images/icons/bell.png'),
  [ICON_TYPES.CALENDAR]: require('../../assets/images/icons/calendar.png'),
  [ICON_TYPES.CHALLENGES_TAB]: require('../../assets/images/icons/challenges_tab.png'),
  [ICON_TYPES.CHALLENGES_TAB_FILLED]: require('../../assets/images/icons/challenges_tab_filled.png'),
  [ICON_TYPES.CHECK_CIRCLE]: require('../../assets/images/icons/check_circle_unfilled.png'),
  [ICON_TYPES.CHECK_CIRCLE_FILLED]: require('../../assets/images/icons/check_circle.png'),
  [ICON_TYPES.CLOSE]: require('../../assets/images/icons/close.png'),
  [ICON_TYPES.COUNTDOWN]: require('../../assets/images/icons/countdown.png'),
  [ICON_TYPES.CROSS]: require('../../assets/images/icons/cross.png'),
  [ICON_TYPES.CYCLING]: require('../../assets/images/icons/cycling.png'),
  [ICON_TYPES.DELETE]: require('../../assets/images/icons/delete.png'),
  [ICON_TYPES.DOWN_ARROW]: require('../../assets/images/icons/down_arrow.png'),
  [ICON_TYPES.DROP_DOWN]: require('../../assets/images/icons/arrow_dropdown.png'),
  [ICON_TYPES.DROP_UP]: require('../../assets/images/icons/arrow_drop_up.png'),
  [ICON_TYPES.EDIT]: require('../../assets/images/icons/edit.png'),
  [ICON_TYPES.EMAIL]: require('../../assets/images/icons/email.png'),
  [ICON_TYPES.ENVELOPE_ICON]: require('../../assets/images/icons/envelope.png'),
  [ICON_TYPES.ERROR]: require('../../assets/images/icons/error.png'),
  [ICON_TYPES.EXIT]: require('../../assets/images/icons/exit.png'),
  [ICON_TYPES.FLAG]: require('../../assets/images/icons/flag.png'),
  [ICON_TYPES.GREEN_TICK]: require('../../assets/images/icons/green_tick.png'),
  [ICON_TYPES.HOME_TAB]: require('../../assets/images/icons/home_tab.png'),
  [ICON_TYPES.HOME_TAB_FILLED]: require('../../assets/images/icons/home_tab_filled.png'),
  [ICON_TYPES.JOINED]: require('../../assets/images/icons/joined.png'),
  [ICON_TYPES.LINK_ICON]: require('../../assets/images/icons/link.png'),
  [ICON_TYPES.LOCK_PASS]: require('../../assets/images/icons/lock_pass.png'),
  [ICON_TYPES.LOCK_QUESTION]: require('../../assets/images/icons/lock_question.png'),
  [ICON_TYPES.MENU]: require('../../assets/images/icons/menu.png'),
  [ICON_TYPES.MESSAGE]: require('../../assets/images/icons/message.png'),
  [ICON_TYPES.MY_CREATE_TEAM]: require('../../assets/images/icons/my_created_team.png'),
  [ICON_TYPES.PEOPLE]: require('../../assets/images/icons/people.png'),
  [ICON_TYPES.PERSON_ICON]: require('../../assets/images/icons/person_icon.png'),
  [ICON_TYPES.RED_CROSS]: require('../../assets/images/icons/red_cross.png'),
  [ICON_TYPES.REWARD_TAB]: require('../../assets/images/icons/reward_tab.png'),
  [ICON_TYPES.REWARD_TAB_FILLED]: require('../../assets/images/icons/reward_tab_filled.png'),
  [ICON_TYPES.REWARD_MEDAL]: require('../../assets/images/icons/reward_medal.png'),
  [ICON_TYPES.REWARD_MEDAL_FILLED]: require('../../assets/images/icons/reward_medal_filled.png'),
  [ICON_TYPES.RUNNING]: require('../../assets/images/icons/running.png'),
  [ICON_TYPES.SAVE]: require('../../assets/images/icons/save.png'),
  [ICON_TYPES.SHARE]: require('../../assets/images/icons/share.png'),
  [ICON_TYPES.SEARCH]: require('../../assets/images/icons/search.png'),
  [ICON_TYPES.SEND]: require('../../assets/images/icons/send.png'),
  [ICON_TYPES.STAR]: require('../../assets/images/icons/star.png'),
  [ICON_TYPES.STAR_FILLED]: require('../../assets/images/icons/star_filled.png'),
  [ICON_TYPES.SYNC]: require('../../assets/images/icons/sync.png'),
  [ICON_TYPES.TEAM]: require('../../assets/images/icons/team.png'),
  [ICON_TYPES.TEAM_TAB]: require('../../assets/images/icons/team_tab.png'),
  [ICON_TYPES.TEAM_TAB_FILLED]: require('../../assets/images/icons/team_tab_filled.png'),
  [ICON_TYPES.THUMB_UP]: require('../../assets/images/icons/thumb_up.png'),
  [ICON_TYPES.TICK]: require('../../assets/images/icons/tick.png'),
  [ICON_TYPES.TICK_2]: require('../../assets/images/icons/tick_2.png'),
  [ICON_TYPES.TICK_PERSON]: require('../../assets/images/icons/tick_person.png'),
  [ICON_TYPES.TILDE_CIRCLE]: require('../../assets/images/icons/tilde_circle.png'),
  [ICON_TYPES.TIMER]: require('../../assets/images/icons/timer.png'),
  [ICON_TYPES.TRACKER_TAB]: require('../../assets/images/icons/tracker_tab.png'),
  [ICON_TYPES.TRACKER_TAB_FILLED]: require('../../assets/images/icons/tracker_tab_filled.png'),
  [ICON_TYPES.UP_ARROW]: require('../../assets/images/icons/up_arrow.png'),
  [ICON_TYPES.VISIBILITY_OFF]: require('../../assets/images/icons/visibility_off.png'),
  [ICON_TYPES.VISIBILITY_ON]: require('../../assets/images/icons/visibility_On.png'),
  [ICON_TYPES.WALKING_BLUE]: require('../../assets/images/icons/walking_blue.png'),
  [ICON_TYPES.WHEEL_CHAIR]: require('../../assets/images/icons/walking.png'),
  [ICON_TYPES.YELLOW_WATCH]: require('../../assets/images/icons/yellow_watch.png'),
};

export type IconTypes = keyof typeof icons;
