const images = {
  appLogo: require('../assets/images/logo.png'),
  errorBg: require('../assets/images/error_bg.png'),
  splashGif: require('../assets/images/splash.gif'),
  user: require('../assets/images/icons/user.png'),
  wellness: require('../assets/images/wellness.png'),
  crwcLogo: require('../assets/images/crwc_logo.png'),
  shadowBack: require('../assets/images/shadow_back.png'),
  headerBack: require('../assets/images/header_back.png'),
  defaultImage: require('../assets/images/default_image.png'),
  bgCRWCTimer: require('../assets/images/boostr_crwc_blue.png'),
  relayChallengeIcon: require('../assets/images/relay_icon.png'),
  blueBackground: require('../assets/images/blue_background.png'),
  defaultImage_2: require('../assets/images/default_image_2.png'),
  menuBackground: require('../assets/images/menu_background.png'),
  discountOffers: require('../assets/images/discount_offers1.png'),
  bgCRWCDistance: require('../assets/images/boostr_crwc_green.png'),
  farOutChallengeIcon: require('../assets/images/far_out_icon.png'),
  loginBackground: require('../assets/images/login_background.png'),
  meetUpChallengeIcon: require('../assets/images/meet_up_icon.png'),
  onboarding3Logo: require('../assets/images/onboarding3_logo.png'),
  titleBackground: require('../assets/images/title_background.png'),
  registerBackground: require('../assets/images/register_background.png'),
  happyFeetChallengeIcon: require('../assets/images/happy_feet_icon.png'),
  timeTrialChallengeIcon: require('../assets/images/time_trial_icon.png'),
  onboarding4Screenshot: require('../assets/images/onboarding4_screenshot.png'),
  onboarding5Screenshot: require('../assets/images/onboarding5_screenshot.png'),
  relayChallengeBackground: require('../assets/images/relay_challenge_background.png'),
  meetUpChallengeBackground: require('../assets/images/meet_up_challenge_background.png'),
  farOutChallengeBackground: require('../assets/images/far_out_challenge_background.png'),
  happyFeetChallengeBackground: require('../assets/images/happy_feet_challenge_background.png'),
  timeTrialChallengeBackground: require('../assets/images/time_trial_challenge_background.png'),
};

export {images};
